### ISSUE TITLE
How to Address WoT Things?

### ISSUE THREAD

**Issue by karx** [w3c/web-thing-protocol#10]
Hey Group,

The Web Things Protocol `MUST` have an associated URI Schema. Read more [here](https://www.w3.org/TR/wot-architecture/#sec-arch-URIs).

Here are my thoughts on the URI schema,
* MUST having provision to have multiple WoT hosted on same network (or provisioned through a single gateway node)
* MUST allow comparisons matching with multiple devices addressable (something like wildcard or resolution scope)
* MUST generate unique identifiers for all devices. (but how about Virtual Things)

I also feel that this URI definition must also address how listing/discoverability of a WoT Thing is happening.

**Comment by benfrancis** [comment]
@karx Thanks for the feedback.

I agree that it should be explicitly mentioned that the Web Thing Protocol must use a URI scheme for resources.

I had briefly considered defining a new URI scheme like `webthing://` which extends HTTP in a similar way to `webdav://` and `caldav://` but I concluded this wasn't necessary because:

1. The Web Thing Protocol only defines a sub-protocol to use over existing protocols like HTTP and WebSockets, not a new protocol. It does not change the existing HTTP methods and headers etc. of the HTTP protocol in any way.
2. Using a new URI scheme may cripple adoption because it would not immediately be supported by existing web clients and servers. By using the existing `http(s)://` and `ws(s)://` URI schemes, existing libraries, clients and servers can support the web thing protocol out of the box.

> The Web Things Protocol MUST have an associated URI Schema. Read more here.

I have addressed this by explicitly mentioning the `http(s)://` and `ws(s)://` URI schemes in the requirements, in https://github.com/w3c/web-thing-protocol/pull/11

> MUST having provision to have multiple WoT hosted on same network (or provisioned through a single gateway node)

This is covered by the [directory/gateway use cases](file:///home/tola/Code/benfrancis/web-thing-protocol/requirements/index.html#wot-gateways-directories) and is implicitly the case by constraining the specification to using the HTTP and WebSocket protocols

> MUST allow comparisons matching with multiple devices addressable (something like wildcard or resolution scope)

I'm not sure exactly what you mean by this?

> MUST generate unique identifiers for all devices. (but how about Virtual Things)

I have addressed this in https://github.com/w3c/web-thing-protocol/pull/11
