### ISSUE TITLE
Question/discussion: Object wrapper for Property payloads

### ISSUE THREAD

**Issue by jtc42** [w3c/web-thing-protocol#14]
Following in from https://github.com/mozilla-iot/wot/issues/143

I think this is a discussion worth having here as it’s one of the major breaking discrepancies between the Mozilla implementation and what the W3C spec seems to suggest.

While keeping the Mozilla protocol would obviously be ideal, there are a number of cases where this object wrapper could prove difficult to work with (e.g. non-JSON data types), and a few reasons I think it’d worth removing from this new spec.

I should clarify here, I’m referring specifically to the wrapper on the response for specific properties. In this case, the property name is already in the URL, so the wrapper seems irrelevant. Additionally, for response such as image files, the wrapper cannot be included anyway, so for consistency I really feel like removing it makes sense.

In the WebSocket API, I think it should stay as in the Mozilla implementation. In that case, the wrapper is used to specify the property name, and effectively takes the role of the URL in the REST API.

In this case, the Thing Description provides information about the media type and optionally a schema in cases where JSON data is returned. The schema directly describes the data without clients needing to infer a wrapper object.

Hopefully this is something others can chime in on!

Thanks all.

**Comment by benfrancis** [comment]
I agree that property resources shouldn't have object wrappers in the Web Thing Protocol's HTTP sub-protocol, so that it matches the defaults in the W3C Thing Description. This will mean that even if a WoT client doesn't know about the Web Thing Protocol but it implements the W3C WoT Thing Description specification's defaults then it should still be able to get and set properties.

> I should clarify here, I’m referring specifically to the wrapper on the response for specific properties. In this case, the property name is already in the URL, so the wrapper seems irrelevant.

Minor point, but there's no requirement that says you have to have the property in name in the property's URL (the specification doesn't enforce any particular URL structure). But it should be possible to differentiate between properties by their URL regardless.

Where things become a bit more complicated is with action queues (i.e. the [Actions resource](https://iot.mozilla.org/wot/#actions-resource) of the Web Thing API) and event logs (i.e. the [Events resource](https://iot.mozilla.org/wot/#events-resource) of the Web Thing API). The W3C Thing Description currently has no way to describe an action queue or event log in the way they are used in the Mozilla's Web Thing API so that's something we'll need to figure out (and is also being discussed by the Thing Description task force. See https://github.com/w3c/wot-thing-description/issues/899, https://github.com/w3c/wot-thing-description/issues/302 and https://github.com/w3c/wot-thing-description/issues/892).

I agree that it makes sense to keep the wrapper in the WebSocket sub-protocol which lacks the additional context of a resource URI given a single WebSocket is shared by multiple interaction affordances.

**Comment by benfrancis** [comment]
I believe this question has been answered, please re-open if further discussion is needed.
