### ISSUE TITLE
Possibility of alternative data encodings

### ISSUE THREAD

**Issue by jtc42** [w3c/web-thing-protocol#7]
I'm not totally sure if this is within the aims of this specification, however it might be useful to discuss the possibility of alternative content encodings for the HTTP API. I'm assuming the common implementation will be a JSON-based API, however there are some cases where larger binary blobs may need to be returned by the Thing. 

In these cases, while base64 encoding is a possibility, this can be inefficient and on some hardware entirely inseasible, even ignoring the additional storage inefficiency.

While I realise that it is not feasible to write an implementation guide for every possible encoding, it might be good to specify that Things MAY allow alternative content encodings such as `application/cbor`, either for returned data, or both requests and returned data.

Please do close this issue if this is out of scope though!

**Comment by benfrancis** [comment]
I'm not sure that the HTTP or WebSocket sub-protocol specifications should define multiple encodings/serialisations, but multiple sub-protocols (presumably with their own defined serialisations) are certainly within the scope of the group's [charter](https://w3c.github.io/web-thing-protocol/charter/).

Some thoughts:
1. In order to guarantee ad-hoc interoperability there needs to be at least one serialisation that all WoT clients and WoT devices support when using a given sub-protocol. Given it's the default serialisation format of a Thing Description, the obvious choice for HTTP and WebSockets is JSON. I've tentatively added this as a requirement in https://github.com/w3c/web-thing-protocol/pull/9.
2. That doesn't necessarily mean that all payloads have to be JSON, only that JSON is what a client will assume by default if no content type is specified*. Note that requirement 3.1.1.7 says "MAY define a way for a WoT client to find out what other protocols and data formats a WoT device supports".
3. For resource constrained devices, it's possible that both HTTP and JSON are too heavyweight. The scope of the group's charter specifically mentions "Evaluation of other potential Web of Things sub-protocols (e.g. for CoAP)". It might make sense for the default serialisation for a CoAP sub-protocol to be something more efficient than JSON, like CBOR.

*A Thing Description can specify alternative content types for forms or link relations. For example, Mozilla's [`Camera`](https://iot.mozilla.org/schemas/#Camera) capability schema includes an [`ImageProperty`](https://iot.mozilla.org/schemas/#ImageProperty) affordance which can link to an image as a binary resource like a JPEG or PNG file, it doesn't need to be base64 encoded inside a JSON payload. The downside of this is that you can't guarantee that a given client will support the non-default content type denoted in the Thing Description, but supported formats for specific use cases could potentially be further constrained by capability schemas (e.g. a camera, microphone or video camera capability could define a list of supported image, audio or video formats respectively). Semantic annotations in a Thing Description can denote that the Thing Description conforms to a given schema.

The current use cases & requirements document is focused on the HTTP & WebSocket sub-protocol deliverables. If in future we explore a CoAP sub-protocol then we could discuss an alternative default serialisation for CoAP as part of that deliverable.

Let me know if you think there's anything else that should be added to the requirements document on this topic.

**Comment by jtc42** [comment]
Okay yeah that all sounds totally sensible. I agree that JSON-as-default is sensible, and just having the option to include additional encodings should be sufficient.

The reason I mention this is because in some of our applications, we want to be able to pass around C-contiguous arrays. They're not human readable, but they're mostly included to then be picked up by some data analysis application on the network. In this case, you really want to include the array bytes alongside a load of metadata. Right now, our default is b64 encoding the bytes, and sending the data as JSON. 

What we _want_ to be able to do is have clients, for example, specify they want a `cbor` response (even just over HTTP) and get the exact same data but with bytes instead of a b64 encoded string returned as a `cbor` payload. If this is still within the spec then we're all good I think. I need to look into how we should specify multiple encodings in the Thing Description, but I assume there's provisions for that already.

Thanks for the detailed response!

**Comment by benfrancis** [comment]
> What we want to be able to do is have clients, for example, specify they want a cbor response (even just over HTTP with the content_type header) and get the exact same data but with bytes instead of a b64 encoded string returned as a cbor payload. If this is still within the spec then we're all good I think. I need to look into how we should specify multiple encodings in the Thing Description, but I assume there's provisions for that already.

That all sounds reasonable, yes. And yes, there is already a way for Thing Descriptions to expose the same data using multiple protocols and content types. Each interaction affordance can specify multiple [`Form`](https://w3c.github.io/wot-thing-description/#form)s. E.g.

```
{
    "@context": "https://www.w3.org/2019/wot/td/v1",
    "title": "My Thing",
    "properties": {
        "status" : {
            "type": "array",
            "forms": [
                {
                    "href": "https://mything.example.com/status",
                    "contentType": "application/json"
                },
                {
                    "href": "https://mything.example.com/status",
                    "contentType": "application/xml"
                },
                {
                    "href": "coaps://mything.example.com/status",
                    "contentType": "application/cbor"
                },
            ]
        }
    }
}
```

Also, a client could explicitly tell the server what MIME type it would prefer in an [`Accept`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept) header of an HTTP request as part of content negotiation.
